In [25]:
import pandas as pd
import numpy as np 
import matplotlib as mpl
import seaborn as sns

import warnings
warnings.simplefilter(action='ignore')

In [26]:
df_socio = pd.read_excel("..\..\Datasets\Processed\Combined_Process_Factors.xlsx", "Socio_factors_processed")
df_cpi = pd.read_excel("..\..\Datasets\Processed\Combined_Process_Factors.xlsx", "CPI_processed")
df_fdi = pd.read_excel("..\..\Datasets\Processed\Combined_Process_Factors.xlsx", "Net_FDI_processed")
df_undernourishment = pd.read_excel("..\..\Datasets\Processed\Combined_Process_Factors.xlsx", "undernourishment_processed")
df_cpi.columns

Index(['M49_Code', 'Country_Name', 'ISO3 Code', 'CPI_Food_2016',
       'CPI_Food_2017', 'CPI_Food_2018', 'CPI_Food_2019', 'CPI_Food_2020',
       'CPI_Food_Avg'],
      dtype='object')

In [27]:
df_cpi.drop(["M49_Code", "ISO3 Code"], inplace=True, axis=1)
df_fdi.drop(["Unnamed: 0", "M49_Code"], inplace=True, axis=1)
df_undernourishment.drop(["Unnamed: 0", "M49_Code"], inplace=True, axis=1)

In [28]:
df_combined = pd.merge(df_socio, df_cpi, on="Country_Name", how="inner")
df_combined = pd.merge(df_combined, df_fdi, on="Country_Name", how="inner")
df_combined = pd.merge(df_combined, df_undernourishment, on="Country_Name", how="inner")
df_combined.columns
# df_combined.to_csv("combined_df.csv")

Index(['ISO3_Code', 'Country_Name', 'M49_Code', 'Life_Expectancy_2016',
       'Life_Expectancy_2017', 'Life_Expectancy_2018', 'Life_Expectancy_2019',
       'Life_Expectancy_2020', 'Life_Expectancy_Avg',
       'Mean_Years_Of_Schooling_2016', 'Mean_Years_Of_Schooling_2017',
       'Mean_Years_Of_Schooling_2018', 'Mean_Years_Of_Schooling_2019',
       'Mean_Years_Of_Schooling_2020', 'Mean_Years_of_Schooling_Avg',
       'CPI_Food_2016', 'CPI_Food_2017', 'CPI_Food_2018', 'CPI_Food_2019',
       'CPI_Food_2020', 'CPI_Food_Avg', 'Total_FDI_Inflows_2016',
       'Total_FDI_Inflows_2017', 'Total_FDI_Inflows_2018',
       'Total_FDI_Inflows_2019', 'Total_FDI_Inflows_2020',
       'Total_FDI_Outflows_2016', 'Total_FDI_Outflows_2017',
       'Total_FDI_Outflows_2018', 'Total_FDI_Outflows_2019',
       'Total_FDI_Outflows_2020', 'Net_FDI_2016', 'Net_FDI_2017',
       'Net_FDI_2018', 'Net_FDI_2019', 'Net_FDI_2020',
       'Prevalence_of_undernourishment_2016',
       'Prevalence_of_undernourishment_2017',
       'Prevalence_of_undernourishment_2018',
       'Prevalence_of_undernourishment_2019',
       'Prevalence_of_undernourishment_2020'],
      dtype='object')

In [44]:
df_all_processed = pd.read_csv("..\..\Datasets\Processed\All_Processed.csv")
df_all_processed.sort_values(["Country_Name", "Year"], inplace=True)

df_gni = pd.read_csv("..\..\Datasets\Original\GNI.csv", encoding="ISO-8859-1")
df_population = pd.read_csv("..\..\Datasets\Original\Population.csv", encoding="ISO-8859-1")
df_govt_exp = pd.read_csv("..\..\Datasets\Original\Govt_Expenditure.csv", encoding="ISO-8859-1")
df_electricity_access = pd.read_csv("..\..\Datasets\Original\Access_To_Electricity.csv", encoding="ISO-8859-1")
df_infant_mortality_rate = pd.read_csv("..\..\Datasets\Original\Infant_Mortality_Rate_Under_5.csv", encoding="ISO-8859-1")
df_unemployment = pd.read_csv("..\..\Datasets\Original/Unemployment.csv", encoding="ISO-8859-1")
df_gni.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "GNI"}, inplace=True)
df_gni.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Unit", "Item"], axis=1, inplace=True)

df_population.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "Population"}, inplace=True)
df_population.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Item", "Unit"], axis=1, inplace=True)

df_govt_exp.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "Govt_Expenditure"}, inplace=True)
df_govt_exp.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Item", "Unit"], axis=1, inplace=True)

# df_electricity_access.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "Access_to_Electricity"}, inplace=True)
# df_electricity_access.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Item", "Unit"], axis=1, inplace=True)

# df_infant_mortality_rate.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "Infant_Mortality_Rate"}, inplace=True)
# df_infant_mortality_rate.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Item", "Unit"], axis=1, inplace=True)

# df_unemployment.rename(columns={"Area Code (M49)": "M49_Code", "Area": "Country_Name", "Value": "Unemployment"}, inplace=True)
# df_unemployment.drop(["Domain Code", "Domain", "Element Code", "Element", "Item Code", "Year Code", 'Flag','Flag Description', 'Note', "M49_Code", "Item", "Unit"], axis=1, inplace=True)

# print(df_faostats.columns)
# print(df_faostats1.columns)
# df_all_processed.columns

df_combined1 = pd.merge(df_all_processed, df_gni, on=["Country_Name", "Year"], how="outer")
df_combined1 = pd.merge(df_combined1, df_population, on=["Country_Name", "Year"], how="outer")
df_combined1 = pd.merge(df_combined1, df_govt_exp, on=["Country_Name", "Year"], how="outer")
# df_combined1 = pd.merge(df_combined1, df_electricity_access, on=["Country_Name", "Year"], how="inner")
# df_combined1 = pd.merge(df_combined1, df_infant_mortality_rate, on=["Country_Name", "Year"], how="inner")
# df_combined1 = pd.merge(df_combined1, df_unemployment, on=["Country_Name", "Year"], how="inner")

,ISO3_Code,Country_Name,M49_Code,Year,Life_Expectancy,Mean_Years_Of_Schooling,CPI_Food,Net_FDI,Prevalence_of_undernourishment,GNI,Population,Govt_Expenditure
0,AFG,Afghanistan,4.0,2016,63.1361,2.463660,108.916832,78.810000,22.2,18199.126228,34636.207,9299.089340
1,AFG,Afghanistan,4.0,2017,63.0160,2.561425,113.832502,42.590000,23.0,19145.017021,35643.418,9095.510866
2,AFG,Afghanistan,4.0,2018,63.0810,2.659189,113.490296,78.910000,24.0,18610.257350,36686.784,NaN
3,AFG,Afghanistan,4.0,2019,63.5645,2.756953,119.067918,12.586666,26.9,19205.244293,37769.499,NaN
4,AFG,Afghanistan,4.0,2020,62.5751,2.854718,128.002089,-24.142135,29.8,19982.204387,38972.230,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1170,NaN,Western Sahara,NaN,2016,NaN,NaN,NaN,NaN,NaN,NaN,505.455,NaN
1171,NaN,Western Sahara,NaN,2017,NaN,NaN,NaN,NaN,NaN,NaN,518.859,NaN
1172,NaN,Western Sahara,NaN,2018,NaN,NaN,NaN,NaN,NaN,NaN,532.004,NaN
1173,NaN,Western Sahara,NaN,2019,NaN,NaN,NaN,NaN,NaN,NaN,544.876,NaN
1174,NaN,Western Sahara,NaN,2020,NaN,NaN,NaN,NaN,NaN,NaN,556.048,NaN

In [42]:
df_combined1.to_csv("combined_df2.csv")