In [9]:
import pandas as pd
import numpy as np 
import matplotlib as mpl
import seaborn as sns

In [10]:
DATASETS = ["SocioFactors_Processed.csv", 
        "CPI_Food_Processed.csv", \
        "Net_FDI_Processed.csv", \
        "Infant_Mortality_Rate_Processed.csv", \
        "Unemployment_Processed.csv", \
        "Access_To_Electricity_Processed.csv", \
        "Fertility_Rate_Processed.csv", \
        "Immunization_Measles_Processed.csv", \
        "Labor_Force_Gender_Ratio_Processed.csv", \
        "Corruption_Perception_Index_Processed.csv", \
        "Prevalence_of_Undernourishment_Processed.csv"]

In [11]:
# Merge all csv files
files = [".\datasets\Processed\%s" % x for x in DATASETS]
try:    
    dfs = [pd.read_csv(file, encoding='utf8') for file in files]
except:
    dfs = [pd.read_csv(file, encoding='ISO-8859-1') for file in files]

# Drop columns
for i in range(1, len(dfs)):
    columns = ["Unnamed: 0", "Country_Name", "ISO3 Code", "ISO3_Code"]
    for col in columns:
        if col in dfs[i].columns:
            dfs[i].drop(columns=[col], inplace=True)
    if "Area Code (M49)" in dfs[i].columns:
        dfs[i].rename(columns={"Area Code (M49)": "M49_Code"}, inplace=True)
    if "Net_FDI" in DATASETS[i]:
        dfs[i].drop(columns=dfs[i].columns[dfs[i].columns.str.contains("Total_FDI")], inplace=True)
for i in range(len(dfs)):
    print(dfs[i].columns)

# Merge
df = dfs[0]
for i in range(1, len(dfs)):
    df = df.merge(dfs[i], on="M49_Code", how="inner")
df

Index(['ISO3_Code', 'Country_Name', 'M49_Code', 'Life_Expectancy_2016',
       'Life_Expectancy_2017', 'Life_Expectancy_2018', 'Life_Expectancy_2019',
       'Life_Expectancy_2020', 'Life_Expectancy_Avg',
       'Mean_Years_Of_Schooling_2016', 'Mean_Years_Of_Schooling_2017',
       'Mean_Years_Of_Schooling_2018', 'Mean_Years_Of_Schooling_2019',
       'Mean_Years_Of_Schooling_2020', 'Mean_Years_of_Schooling_Avg'],
      dtype='object')
Index(['M49_Code', 'CPI_Food_2016', 'CPI_Food_2017', 'CPI_Food_2018',
       'CPI_Food_2019', 'CPI_Food_2020', 'CPI_Food_Avg'],
      dtype='object')
Index(['M49_Code', 'Net_FDI_2016', 'Net_FDI_2017', 'Net_FDI_2018',
       'Net_FDI_2019', 'Net_FDI_2020'],
      dtype='object')
Index(['M49_Code', 'Infant_Mortality_Rate_2016', 'Infant_Mortality_Rate_2017',
       'Infant_Mortality_Rate_2018', 'Infant_Mortality_Rate_2019',
       'Infant_Mortality_Rate_2020', 'Infant_Mortality_Rate_Avg'],
      dtype='object')
Index(['M49_Code', 'Unemployment_2016', 'Unemployment_2017',
       'Unemployment_2018', 'Unemployment_2019', 'Unemployment_2020',
       'Unemployment_Avg'],
      dtype='object')
Index(['M49_Code', 'Access_To_Electricity_2016', 'Access_To_Electricity_2017',
       'Access_To_Electricity_2018', 'Access_To_Electricity_2019',
       'Access_To_Electricity_2020', 'Access_To_Electricity_Avg'],
      dtype='object')
Index(['M49_Code', 'Fertility_Rate_2016', 'Fertility_Rate_2017',
       'Fertility_Rate_2018', 'Fertility_Rate_2019', 'Fertility_Rate_2020',
       'Fertility_Rate_Avg'],
      dtype='object')
Index(['M49_Code', 'Immunization_Measles_2016', 'Immunization_Measles_2017',
       'Immunization_Measles_2018', 'Immunization_Measles_2019',
       'Immunization_Measles_2020', 'Immunization_Measles_Avg'],
      dtype='object')
Index(['M49_Code', 'Labor_Force_Gender_Ratio_2016',
       'Labor_Force_Gender_Ratio_2017', 'Labor_Force_Gender_Ratio_2018',
       'Labor_Force_Gender_Ratio_2019', 'Labor_Force_Gender_Ratio_2020',
       'Labor_Force_Gender_Ratio_Avg'],
      dtype='object')
Index(['M49_Code', 'Corruption_Perception_Index_2020',
       'Corruption_Perception_Index_2019', 'Corruption_Perception_Index_2018',
       'Corruption_Perception_Index_2017', 'Corruption_Perception_Index_2016',
       'Corruption_Perception_Index_Avg'],
      dtype='object')
Index(['M49_Code', 'Prevalence_of_undernourishment_2016',
       'Prevalence_of_undernourishment_2017',
       'Prevalence_of_undernourishment_2018',
       'Prevalence_of_undernourishment_2019',
       'Prevalence_of_undernourishment_2020'],
      dtype='object')

,ISO3_Code,Country_Name,M49_Code,Life_Expectancy_2016,Life_Expectancy_2017,Life_Expectancy_2018,Life_Expectancy_2019,Life_Expectancy_2020,Life_Expectancy_Avg,Mean_Years_Of_Schooling_2016,...,Corruption_Perception_Index_2019,Corruption_Perception_Index_2018,Corruption_Perception_Index_2017,Corruption_Perception_Index_2016,Corruption_Perception_Index_Avg,Prevalence_of_undernourishment_2016,Prevalence_of_undernourishment_2017,Prevalence_of_undernourishment_2018,Prevalence_of_undernourishment_2019,Prevalence_of_undernourishment_2020
0,AFG,Afghanistan,4.0,63.1361,63.0160,63.0810,63.5645,62.5751,63.07454,2.463660,...,16.0,16.0,15.0,15.0,16.2,22.2,23.0,24.0,26.9,29.8
1,AGO,Angola,24.0,61.0923,61.6798,62.1438,62.4484,62.2612,61.92510,5.417391,...,26.0,19.0,19.0,18.0,21.8,15.4,15.4,15.7,17.9,20.8
2,ALB,Albania,8.0,78.8602,79.0473,79.1838,79.2825,76.9893,78.67262,10.727528,...,35.0,36.0,38.0,39.0,36.8,4.7,4.7,4.6,4.3,3.9
3,ARE,United Arab Emirates,784.0,79.3347,79.5036,79.6274,79.7262,78.9457,79.42752,10.842620,...,71.0,70.0,71.0,66.0,69.8,6.3,6.4,6.2,6.0,5.6
4,ARG,Argentina,32.0,76.3077,76.8330,76.9994,77.2845,75.8921,76.66334,10.928190,...,45.0,40.0,39.0,36.0,40.4,2.6,3.1,3.4,3.5,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,VEN,Venezuela (Bolivarian Republic of),862.0,72.0578,71.9430,71.9788,72.1614,71.0949,71.84718,10.312300,...,16.0,18.0,18.0,17.0,16.8,16.4,22.2,22.7,24.9,22.9
144,VNM,Viet Nam,704.0,73.9382,73.9632,73.9757,74.0929,75.3779,74.26958,8.122675,...,37.0,33.0,35.0,33.0,34.8,7.8,7.2,6.8,6.2,5.7
145,VUT,Vanuatu,548.0,69.6496,69.7095,69.7948,69.8769,70.2995,69.86606,6.680000,...,46.0,46.0,43.0,NaN,44.5,11.2,12.3,12.6,12.4,11.9
146,YEM,Yemen,887.0,66.0641,65.9573,64.5751,65.0917,64.6501,65.26766,3.000000,...,15.0,14.0,16.0,14.0,14.8,46.1,46.6,44.7,42.8,41.4
147,ZAF,South Africa,710.0,64.7469,65.4020,65.6743,66.1750,65.2522,65.45008,10.187880,...,44.0,43.0,43.0,45.0,43.8,5.4,5.5,5.7,6.3,6.9

## Preprocessing

In [12]:
# Replace all null values by mean
df.fillna(df.mean(), inplace=True)
df.isnull().sum()

C:\Users\admin\AppData\Local\Temp\ipykernel_45112\1916672156.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

ISO3_Code                              0
Country_Name                           0
M49_Code                               0
Life_Expectancy_2016                   0
Life_Expectancy_2017                   0
                                      ..
Prevalence_of_undernourishment_2016    0
Prevalence_of_undernourishment_2017    0
Prevalence_of_undernourishment_2018    0
Prevalence_of_undernourishment_2019    0
Prevalence_of_undernourishment_2020    0
Length: 73, dtype: int64

## Convert to excel format

In [13]:
# Create dataframes corr. to each year
import csv

df_exc = df.copy()
df_exc = df_exc.loc[:, ~df_exc.columns.str.contains('Avg')]
col_names = df_exc.columns[:3].tolist() + ["Year"] + [x.replace("_2020", "") for x in df_exc.columns[df_exc.columns.str.contains('_2020')].values]
print(col_names)
n = np.count_nonzero(df_exc.columns.str.contains('_2020')) + 4
years = [2016, 2017, 2018, 2019, 2020]
dfs = [None, None, None, None, None]
data = []
for i, year in enumerate(years):
    df_info = df_exc.iloc[:, 0:3]
    df_info["Year"] = year
    dfs[i] = pd.concat([df_info, df_exc.loc[:, df_exc.columns.str.contains(str(year))]], axis=1)
    assert dfs[i].shape[1] == n
    data += dfs[i].values.tolist()
data = [col_names] + data
with open("./datasets/Processed/All_Processed.csv", "w", encoding="utf8", newline="") as f:
   w = csv.writer(f)
   w.writerows(data)

['ISO3_Code', 'Country_Name', 'M49_Code', 'Year', 'Life_Expectancy', 'Mean_Years_Of_Schooling', 'CPI_Food', 'Net_FDI', 'Infant_Mortality_Rate', 'Unemployment', 'Access_To_Electricity', 'Fertility_Rate', 'Immunization_Measles', 'Labor_Force_Gender_Ratio', 'Corruption_Perception_Index', 'Prevalence_of_undernourishment']